### ISSUE TITLE
SolidEdgeConstants (C#)

### ISSUE THREAD

**Issue by lwsmart** [SolidEdgeCommunity/SDK#1]
When I try to build the DemoAddIn, I get an error stating that 'ApplicationCommandConstants' in the namespace 'SolidEdgeConstants' is missing.
![SolidEdgeConstants](https://user-images.githubusercontent.com/82518127/114714962-3631fc00-9cf8-11eb-8687-bad789a461e0.JPG)

**Comment by jlnewell** [comment]
The SDK\Samples will always be built with the latest version of the software. If you are using an older version, adapt the code as needed to meet your needs.

**Comment by lwsmart** [comment]
Jason, thank you for replying to this issue so quickly.  In your comment, you mentioned "the latest version of the software".  Are you referring to Solid Edge software?  I'm running version 2020, so to make the SDK/Samples run as is, I need to download version 2021???

**Comment by jlnewell** [comment]
The samples that I provide will always be using the latest version of Solid Edge. In this case, Solid Edge 2021. If you have a need to run the samples that are provided in an older version of Solid Edge, you will need to make the necessary code changes.

**Comment by lwsmart** [comment]
I have upgraded to version 2021 and SDK\Samples is working correctly.

Thanks for your help.
